use axum::extract::ws::{Message, WebSocket};
use serde::{Deserialize, Serialize};
use str0m::change::{SdpAnswer, SdpOffer};

/// Messages the client sends to the server.
#[derive(Debug, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ClientMsg {
    /// Step 1: pair with the 6-digit code shown on the server console.
    Pair { code: String },
    /// Step 3: send the SDP answer in response to the offer.
    Answer { sdp: SdpAnswer },
    /// Optional trickle ICE candidate (string representation).
    Ice { candidate: String },
}

/// Messages the server sends to the client.
#[derive(Debug, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ServerMsg {
    /// Step 2: SDP offer sent after successful pairing.
    Offer { sdp: SdpOffer },
    /// Returned instead of an offer when the pairing code is wrong.
    Error { msg: String },
}

/// Send a JSON-serialisable value over a WebSocket connection.
///
/// Returns `None` if serialisation or sending failed.
pub async fn send_json<T: Serialize>(ws: &mut WebSocket, msg: &T) -> Option<()> {
    let text = serde_json::to_string(msg).ok()?;
    ws.send(Message::Text(text.into())).await.ok()
}

/// Wait for the next text message from the client and deserialise it.
///
/// Pings/Pongs are silently skipped. Returns `None` on close or error.
pub async fn recv_json<T: for<'de> Deserialize<'de>>(ws: &mut WebSocket) -> Option<T> {
    loop {
        match ws.recv().await? {
            Ok(Message::Text(text)) => return serde_json::from_str(&text).ok(),
            Ok(Message::Close(_)) | Err(_) => return None,
            Ok(_) => continue, // skip Ping/Pong/Binary
        }
    }
}

/// Run the WebSocket signaling handshake.
///
/// Protocol:
/// 1. Receive `pair` from client — validates the code against `expected_code`.
/// 2. Send `offer` (the SDP generated by the caller).
/// 3. Receive `answer` from client.
///
/// Returns `Some(SdpAnswer)` on success, `None` if any step fails.
pub async fn run_handshake(
    ws: &mut WebSocket,
    expected_code: &str,
    offer: SdpOffer,
) -> Option<SdpAnswer> {
    // Step 1: validate pairing code
    match recv_json::<ClientMsg>(ws).await? {
        ClientMsg::Pair { code } if code == expected_code => {}
        ClientMsg::Pair { .. } => {
            let _ = send_json(
                ws,
                &ServerMsg::Error {
                    msg: "Invalid pairing code".into(),
                },
            )
            .await;
            return None;
        }
        _ => {
            let _ = send_json(
                ws,
                &ServerMsg::Error {
                    msg: "Expected pair message".into(),
                },
            )
            .await;
            return None;
        }
    }

    // Step 2: send offer
    send_json(ws, &ServerMsg::Offer { sdp: offer }).await?;

    // Step 3: receive answer
    match recv_json::<ClientMsg>(ws).await? {
        ClientMsg::Answer { sdp } => Some(sdp),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn client_pair_round_trips() {
        let msg = ClientMsg::Pair {
            code: "123456".into(),
        };
        let json = serde_json::to_string(&msg).unwrap();
        assert!(json.contains("\"type\":\"pair\""));
        assert!(json.contains("\"code\":\"123456\""));

        let parsed: ClientMsg = serde_json::from_str(&json).unwrap();
        assert!(matches!(parsed, ClientMsg::Pair { code } if code == "123456"));
    }

    #[test]
    fn server_error_round_trips() {
        let msg = ServerMsg::Error {
            msg: "Invalid pairing code".into(),
        };
        let json = serde_json::to_string(&msg).unwrap();
        assert!(json.contains("\"type\":\"error\""));

        let parsed: ServerMsg = serde_json::from_str(&json).unwrap();
        assert!(matches!(parsed, ServerMsg::Error { msg } if msg.contains("Invalid")));
    }

    #[test]
    fn client_ice_round_trips() {
        let msg = ClientMsg::Ice {
            candidate: "candidate:1 1 UDP ...".into(),
        };
        let json = serde_json::to_string(&msg).unwrap();
        assert!(json.contains("\"type\":\"ice\""));

        let parsed: ClientMsg = serde_json::from_str(&json).unwrap();
        assert!(matches!(parsed, ClientMsg::Ice { .. }));
    }

    #[test]
    fn unknown_type_deserializes_to_error() {
        let json = r#"{"type":"unknown","foo":"bar"}"#;
        let result: Result<ClientMsg, _> = serde_json::from_str(json);
        assert!(result.is_err(), "unknown type should fail to deserialise");
    }
}
